export const polygonDidRegistryABI = [{
  "type": "event",
  "name": "DidCreated",
  "inputs": [{
    "type": "address",
    "name": "id",
    "internalType": "address",
    "indexed": false
  }, {
    "type": "string",
    "name": "doc",
    "internalType": "string",
    "indexed": false
  }],
  "anonymous": false
}, {
  "type": "event",
  "name": "DidDeleted",
  "inputs": [{
    "type": "address",
    "name": "id",
    "internalType": "address",
    "indexed": false
  }],
  "anonymous": false
}, {
  "type": "event",
  "name": "DidUpdated",
  "inputs": [{
    "type": "address",
    "name": "id",
    "internalType": "address",
    "indexed": false
  }, {
    "type": "string",
    "name": "doc",
    "internalType": "string",
    "indexed": false
  }],
  "anonymous": false
}, {
  "type": "function",
  "stateMutability": "nonpayable",
  "payable": false,
  "outputs": [{
    "type": "address",
    "name": "controller",
    "internalType": "address"
  }, {
    "type": "uint256",
    "name": "created",
    "internalType": "uint256"
  }, {
    "type": "uint256",
    "name": "updated",
    "internalType": "uint256"
  }, {
    "type": "string",
    "name": "did_doc",
    "internalType": "string"
  }],
  "name": "createDID",
  "inputs": [{
    "type": "address",
    "name": "_id",
    "internalType": "address"
  }, {
    "type": "string",
    "name": "_doc",
    "internalType": "string"
  }],
  "constant": false
}, {
  "type": "function",
  "stateMutability": "nonpayable",
  "payable": false,
  "outputs": [],
  "name": "deleteDID",
  "inputs": [{
    "type": "address",
    "name": "_id",
    "internalType": "address"
  }],
  "constant": false
}, {
  "type": "function",
  "stateMutability": "view",
  "payable": false,
  "outputs": [{
    "type": "string",
    "name": "",
    "internalType": "string"
  }],
  "name": "getDID",
  "inputs": [{
    "type": "address",
    "name": "_id",
    "internalType": "address"
  }],
  "constant": true
}, {
  "type": "function",
  "stateMutability": "nonpayable",
  "payable": false,
  "outputs": [{
    "type": "address",
    "name": "controller",
    "internalType": "address"
  }, {
    "type": "uint256",
    "name": "created",
    "internalType": "uint256"
  }, {
    "type": "uint256",
    "name": "updated",
    "internalType": "uint256"
  }, {
    "type": "string",
    "name": "did_doc",
    "internalType": "string"
  }],
  "name": "updateDID",
  "inputs": [{
    "type": "address",
    "name": "_id",
    "internalType": "address"
  }, {
    "type": "string",
    "name": "_doc",
    "internalType": "string"
  }],
  "constant": false
}];